from __future__ import annotations

import asyncio
import logging
from datetime import datetime

from app import deps
from app.models import AlertPayload

logger = logging.getLogger(__name__)

# In-memory report store: report_id -> AlertPayload
_report_store: dict[str, AlertPayload] = {}


def store_report(alert: AlertPayload) -> str:
    report_id = f"r_{id(alert)}_{int(datetime.now().timestamp())}"
    _report_store[report_id] = alert
    return report_id


def get_report(report_id: str) -> AlertPayload | None:
    return _report_store.get(report_id)


async def followup_question(report_id: str, question: str) -> str | None:
    """Ask a follow-up question about an existing report."""
    alert = get_report(report_id)
    if not alert or not alert.deep_analysis:
        return None

    from app.analysis.deepseek_client import DeepSeekClient
    client = DeepSeekClient(deps.settings)

    system_prompt = (
        "你是一位专业的金融市场分析师。用户正在对之前的研报进行追问。"
        "请基于已有研报内容回答问题，如果问题超出研报范围，可以补充新的分析。使用中文回答。"
    )
    user_prompt = (
        f"原始新闻：{alert.news_item.title}\n"
        f"情绪得分：{alert.sentiment.score} ({alert.sentiment.label})\n"
        f"已有研报：\n{alert.deep_analysis}\n\n"
        f"用户追问：{question}"
    )

    try:
        result = await asyncio.wait_for(
            client.analyze(system_prompt, user_prompt),
            timeout=30,
        )
        return result
    except Exception as e:
        logger.error("Follow-up question error: %s", e)
        return None


def export_markdown(report_id: str) -> str | None:
    """Export a report as Markdown."""
    alert = get_report(report_id)
    if not alert:
        return None

    lines = [
        f"# {alert.news_item.title}",
        "",
        f"**来源**: {alert.news_item.source}  ",
        f"**情绪得分**: {alert.sentiment.score:.3f} ({alert.sentiment.label})  ",
        f"**置信度**: {alert.sentiment.confidence:.3f}  ",
        f"**告警级别**: {alert.alert_level}  ",
        f"**触发关键词**: {', '.join(alert.triggered_keywords)}  ",
        f"**时间**: {alert.created_at.strftime('%Y-%m-%d %H:%M:%S')}",
        "",
    ]

    if alert.news_item.url:
        lines.append(f"**链接**: [{alert.news_item.url}]({alert.news_item.url})")
        lines.append("")

    if alert.news_item.content_snippet:
        lines.append("## 新闻摘要")
        lines.append("")
        lines.append(alert.news_item.content_snippet)
        lines.append("")

    if alert.deep_analysis:
        lines.append("## 深度研报")
        lines.append("")
        lines.append(alert.deep_analysis)
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by Market Sentiment Monitor at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")

    return "\n".join(lines)


async def multi_model_compare(report_id: str) -> dict | None:
    """Run a second model analysis for cross-validation (uses same DeepSeek with different temperature)."""
    alert = get_report(report_id)
    if not alert:
        return None

    from app.analysis.deepseek_client import DeepSeekClient
    from config.settings import Settings

    # Create a second client with higher temperature for diverse perspective
    settings = Settings(
        deepseek_api_key=deps.settings.deepseek_api_key,
        deepseek_model=deps.settings.deepseek_model,
        deepseek_temperature=0.8,
        deepseek_max_tokens=1024,
    )
    client = DeepSeekClient(settings)

    system_prompt = "你是一位持相反立场的分析师（魔鬼代言人），请从相反角度审视这条新闻的市场影响。使用中文回答。"
    user_prompt = (
        f"新闻：{alert.news_item.title}\n"
        f"摘要：{alert.news_item.content_snippet}\n"
        f"情绪：{alert.sentiment.score} ({alert.sentiment.label})\n"
        f"已有研报：{alert.deep_analysis or '无'}\n\n"
        "请提供相反视角的分析。"
    )

    try:
        result = await asyncio.wait_for(
            client.analyze(system_prompt, user_prompt),
            timeout=30,
        )
        return {
            "contrarian_view": result,
            "original_score": alert.sentiment.score,
            "original_label": alert.sentiment.label,
        }
    except Exception as e:
        logger.error("Multi-model compare error: %s", e)
        return None
